# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import image

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_mo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mo.setGeometry(QtCore.QRect(390, 460, 93, 28))
        self.btn_mo.setObjectName("btn_mo")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(640, 70, 151, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.xoa = QtWidgets.QPushButton(self.centralwidget)
        self.xoa.setGeometry(QtCore.QRect(60, 460, 93, 28))
        self.xoa.setObjectName("xoa")
        self.thoat = QtWidgets.QPushButton(self.centralwidget)
        self.thoat.setGeometry(QtCore.QRect(620, 470, 93, 28))
        self.thoat.setObjectName("thoat")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 180, 111, 61))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 70, 191, 151))
        self.label_2.setStyleSheet("image: url(:/lamp/lamp_off - Copy.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(90, 210, 141, 22))
        self.horizontalSlider.setMaximum(3)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setSliderPosition(0)
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setObjectName("horizontalSlider")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.horizontalSlider.valueChanged[int].connect(self.keo)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_mo.setText(_translate("MainWindow", "open"))
        self.xoa.setText(_translate("MainWindow", "clear"))
        self.thoat.setText(_translate("MainWindow", "exit"))
    def keo(self,value):
        if(value==0):
            self.label_2.setStyleSheet("image: url(:/lamp/lamp_off - Copy.png);")   
        elif(value==1):
            self.label_2.setStyleSheet("image: url(:/lamp/lamp_on1 - Copy.png);")
        elif(value==2):
            self.label_2.setStyleSheet("image: url(:/lamp/lamp_on2.png);")
        elif(value==3):
            self.label_2.setStyleSheet("image: url(:/lamp/lamp_on3.png);")
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
