# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testchenlink.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyrebase
firebaseConfig = {
  'apiKey': "AIzaSyAI8YUuPTR-_b6nfwt8_dRu3WO66QewiBc",
  'authDomain': "iot1-a2347.firebaseapp.com",
  'databaseURL': "https://nhet-9909b-default-rtdb.firebaseio.com",
  'projectId': "iot1-a2347",
  'storageBucket': "iot1-a2347.appspot.com",
  'messagingSenderId': "812756037992",
  'appId': "1:812756037992:web:61471e9d7530c6a56fa6dd",
  'measurementId': "G-S3F707CFML"
};
firebase=pyrebase.initialize_app(firebaseConfig)
db=firebase.database()
doam=db.child("doam").get().val()
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 180, 111, 61))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(390, 240, 121, 71))
        self.label_3.setStyleSheet("background: transparent; font-family: 'Times New Roman'; font-size: 12pt;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label_3.setText(f"độ ẩm:{doam}")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
