# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testchart2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib.pyplot as plt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 180, 111, 61))
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(580, 80, 201, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.open = QtWidgets.QPushButton(self.centralwidget)
        self.open.setGeometry(QtCore.QRect(830, 400, 93, 28))
        self.open.setObjectName("open")
        self.open.clicked.connect(self.show_diagram)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open.setText(_translate("MainWindow", "open"))    
    def show_diagram(self):

        # thang = [1, 2 , 3, 4, 5]
        # tien = [200, 400, 124, 600, 879]
        # fig, ax = plt.subplots(figsize=(0.51,0.51))
        # ax.plot(thang, tien)
        # ax.set_xlabel('Tháng')
        # ax.set_ylabel('Tiền')
        # ax.set_title('Biểu đồ tiền điện theo tháng')
        thoi_gian = ['1h', '2h', '3h', '4h', '5h']  # Thời gian
        nhiet_do = [22, 24, 20, 23, 25]  # Nhiệt độ tương ứng (độ C
        fig, ax=plt.subplots()
        ax.bar(thoi_gian, nhiet_do, color='skyblue')
        ax.set_title('Biểu đồ Nhiệt độ theo Thời gian')
        ax.set_xlabel('Thời gian (h)')
        ax.set_ylabel('Nhiệt độ (°C)')
        canvas = FigureCanvas(fig)
        self.verticalLayout.addWidget(canvas)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
